title = "وبلاگ بهزاد شکوری"
baseURL = "https://behzad-shakouri.github.io/"

# تنظیم زبان پیش‌فرض
defaultContentLanguage = "fa"
defaultContentLanguageInSubdir = false

[languages]
  [languages.fa]
    weight = 1
    languageCode = "fa-IR"
    languageName = "فارسی"
    contentDir = "content/fa"
    dir = "rtl"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
mainSections = ["posts"]

[module]
  [[module.imports]]
    path = "github.com/hugo-fixit/FixIt"
