# -------------------------------------------------------------------------------------
# Hugo Configuration
# -------------------------------------------------------------------------------------

title = "وبلاگ بهزاد شکوری"
baseURL = "https://behzad-shakouri.github.io/"

# تنظیم زبان اصلی و راست‌چین
defaultContentLanguage = "fa"
locale = "fa-IR"

[languages]
  [languages.fa]
    weight = 1
    locale = "fa-IR"
    label = "فارسی"
    languageName = "فارسی"
    contentDir = "content"

# تنظیمات عمومی و سئو
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
mainSections = ["posts"]

# تنظیمات ماژول و اتصال قالب FixIt
[module]
  [[module.imports]]
    path = "github.com/hugo-fixit/FixIt"
