# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/configuration/all/
# -------------------------------------------------------------------------------------

# عنوان وبلاگ شما (می‌توانید متن دلخواه خود را بنویسید)
title = "وبلاگ من"

# آدرس وبلاگ شما (یوزرنیم گیت‌هاب خود را به جای username قرار دهید)
baseURL = "https://behzad-shakouri.github.io/"

# تنظیم زبان اصلی وبلاگ روی فارسی (این بخش وبلاگ را راست‌چین می‌کند)
defaultContentLanguage = "fa"
languageCode = "fa-ir"
languageName = "فارسی"

# پشتیبانی از ایموجی‌ها
enableEmoji = true

# استفاده از کدهای Commit گیت برای تاریخ بروزرسانی
enableGitInfo = true

# ساخت فایل robots.txt برای سئو
enableRobotsTXT = true

# بخش اصلی مطالب وبلاگ
mainSections = ["posts"]
