title: "وبلاگ شخصی من"
description: "جایی برای نوشتن، فکر کردن و یادداشت‌های شخصی"

# قالب Minimal Mistakes
remote_theme: "mmistakes/minimal-mistakes"

# پلاگین‌های لازم برای GitHub Pages
plugins:
  - jekyll-include-cache

# تنظیمات فارسی و راست‌چین
locale: "fa"
direction: "rtl"

# اطلاعات نویسنده
author:
  name: "Behzad Shakouri"
  bio: "وبلاگ‌نویس، علاقه‌مند به اپن‌سورس و سیستم‌فکری"

# فعال‌سازی پروفایل نویسنده در صفحه اصلی
author_profile: true

# فعال‌سازی منوی بالای سایت
navigation:
  - title: "خانه"
    url: /
  - title: "درباره من"
    url: /about/
  - title: "یادداشت‌ها"
    url: /posts/
  - title: "دسته‌بندی‌ها"
    url: /categories/
  - title: "تماس"
    url: /contact/


# حالت روشن پیش‌فرض + دکمهٔ تغییر حالت
minimal_mistakes_skin: "default"
enable_darkmode_toggle: true

# فعال‌سازی نوار کناری
sidebar:
  nav: "docs"
  sticky: true

# نمایش سه پست آخر در نوار کناری
recent_posts:
  enabled: true
  count: 3

# فعال‌سازی پست قبلی/بعدی
pagination:
  enabled: true
  prev_label: "پست قبلی"
  next_label: "پست بعدی"

